const apiBaseUrl = 'https://api.stg.ziggle.gistory.me';
const _idpClientId = 'ziggle2023';
const idpRedirectScheme = 'ziggle-idp-login-redirect';
// const idpUrl = 'https://gistory-idp-fe.pages.dev/'
const idpUrl = 'https://infoteam-idp.web.app/'
    '?client_id=$_idpClientId'
    '&redirect_uri=ziggle'
    '&scheme=$idpRedirectScheme'
    '&staging=true';
const placeholderUserName = '엄준식';
