name: build and publish to TestFlight

on:
  push:

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: macos-latest
    concurrency:
      group: staging
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.MATCH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'

      - name: Run fastlane
        run: |
          bundle install
          bundle exec fastlane internal
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        working-directory: ./ios
