name: build and publish to TestFlight

on:
  push:

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: write key
        run: echo "${{ secrets.MATCH_KEY }}" > ./match_key

      - name: Run fastlane
        run: |
          bundle install
          bundle exec fastlane internal
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ../match_key
        working-directory: ./ios
