name: build and publish to TestFlight

on:
  push:
    branches:
      - development

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: macos-latest
    concurrency:
      group: staging
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CERTIFICATION_DEPLOY_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'

      - name: Run fastlane
        run: |
          bundle install
          bundle exec fastlane internal
        env:
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SLACK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        working-directory: ./ios

      - name: action-slack
        uses: 8398a7/action-slack@v3
        if: ${{ failure() || cancelled() }}
        with:
          status: ${{ job.status }}
          author_name: Github Action Build
          mention: ${{ secrets.SLACK_MENTION }}}
          if_mention: 'failure,cancelled'
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
