name: build and publish to TestFlight

on:
  push:

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'

      - name: write key
        run: |
          echo "${{ secrets.MATCH_KEY }}" > ./match_key
          chmod 400 ./match_key

      - name: Run fastlane
        run: |
          bundle install
          bundle exec fastlane internal
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ../match_key
        working-directory: ./ios
